#!/usr/bin/env bash
# Run the relayer and the bridge UI.
#
# The relayer is the same binary the testnet runs, with proving switched off. The scanner,
# the finality gate and the trigger are untouched: a TEE ISM verifies the enclave's quote
# itself, so the only thing removed is the Groth16 wrapper around it.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

need docker
need jq
need curl

# A pruned image or build tree must not be a broken devnet.
"$(dirname "${BASH_SOURCE[0]}")/10-celestia-up.sh"

has ism-celestia-sepolia || die "no tee ism; run 'make init' first"

SEPOLIA_RPC="${SEPOLIA_RPC:-https://ethereum-sepolia-rpc.publicnode.com}"

# An archive endpoint for Sepolia, which this route cannot run without.
#
# The relayer proves the origin merkle tree at the ISM's trusted height, and that height is a
# finalized block - around seventy behind head. Every free Sepolia endpoint measured serves
# eth_getProof for the head block only, so the read that matters is always outside the window.
# This is the same constraint the testnet deployment documents for its L2 origins.
#
# ALCHEMY_API_KEY comes from devnet/.env, which lib.sh has already sourced.
if [ -z "${SEPOLIA_ARCHIVE:-}" ] && [ -n "${ALCHEMY_API_KEY:-}" ]; then
  SEPOLIA_ARCHIVE="https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
fi
if [ -z "${SEPOLIA_ARCHIVE:-}" ]; then
  warn "no Sepolia archive endpoint. Set ALCHEMY_API_KEY in ${ENV_FILE} (copy it from"
  warn "devnet/.env.example), or set SEPOLIA_ARCHIVE directly. Without one the route cannot"
  warn "read state proofs at its trusted height and every scan will fail."
else
  probe="$(curl -s -m 15 -X POST "${SEPOLIA_ARCHIVE}" -H 'content-type: application/json' \
    -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' 2>/dev/null || true)"
  case "${probe}" in
    *'"result"'*) say "sepolia archive reachable" ;;
    *) warn "sepolia archive did not answer: $(printf '%s' "${probe}" | head -c 160)" ;;
  esac
fi
SEPOLIA_BEACON="${SEPOLIA_BEACON:-https://ethereum-sepolia-beacon-api.publicnode.com}"
SEPOLIA_MAILBOX="${SEPOLIA_MAILBOX:-0xfFAEF09B3cd11D9b20d1a19bECca54EEC2884766}"
SEPOLIA_MERKLE_HOOK="${SEPOLIA_MERKLE_HOOK:-0x4917a9746A7B6E0A57159cCb7F5a6744247f2d0d}"
# Which storage slot the hook's incremental tree starts at. Deployment-specific: Hyperlane's
# canonical Sepolia hook uses 103, other deployments use 151. Wrong here and the reader
# reconstructs a tree that does not match the one the contract reports.
SEPOLIA_BASE_SLOT="${SEPOLIA_BASE_SLOT:-$(has origin-merkle-slot && load origin-merkle-slot || echo 103)}"
TICK_SECS="${TICK_SECS:-6}"

CONFIG="${STATE_DIR}/coprocessor.toml"

say "writing ${CONFIG}"
cat > "${CONFIG}" <<TOML
# Generated by 'make start'. Regenerated each run from what 'make init' deployed, so editing
# it by hand does not survive a restart.
tick_secs = ${TICK_SECS}
celestia_lag = 2
proof_dir = "${STATE_DIR}/proofs"

[[routes]]
name = "sepolia-to-celestia"
tee_node_url = "$(load enclave-url)"
ism_id = "$(load ism-celestia-sepolia)"
merkle_tree_address = "$(load sepolia-merkle-hook)"
# Proving is off: the destination verifies the quote directly.
attest_only = true
routers = []

[routes.origin]
kind = "ethereum"
domain = ${SEPOLIA_DOMAIN}
# Both point at the archive, and not only for reads at the trusted height.
#
# The block the enclave attests is Ethereum's *finalized* head, which is around seventy
# blocks behind the chain head. Free endpoints serve eth_getProof for the head block alone,
# so the proof at the attested head is outside their window just as the historical one is.
# One archive endpoint answers both.
execution_rpc = "${SEPOLIA_ARCHIVE:-${SEPOLIA_RPC}}"
archive_rpc = "${SEPOLIA_ARCHIVE:-${SEPOLIA_RPC}}"
beacon_rpc = "${SEPOLIA_BEACON}"
mailbox = "${SEPOLIA_MAILBOX}"
merkle_tree_hook = "${SEPOLIA_MERKLE_HOOK}"
merkle_tree_base_slot = ${SEPOLIA_BASE_SLOT}

[routes.destination]
kind = "celestia"
domain = ${CELESTIA_DOMAIN}
rpc = "${CELESTIA_RPC}"
grpc = "http://localhost:9090"
mailbox_id = "$(load mailbox-id)"
merkle_tree_hook_id = "$(load merkle-hook-id)"
ism_module = "teeism"
TOML

mkdir -p "${STATE_DIR}/proofs" "${STATE_DIR}/logs"

# Replace anything left running, so 'make start' twice does not leave two relayers competing
# for the same route.
for pidfile in relayer ui; do
  if [ -f "${STATE_DIR}/${pidfile}.pid" ]; then
    kill "$(cat "${STATE_DIR}/${pidfile}.pid")" 2>/dev/null || true
    rm -f "${STATE_DIR}/${pidfile}.pid"
  fi
done
pkill -f "tee-hyperlane run --config" 2>/dev/null || true

say "starting the relayer"
(
  cd "${REPO_DIR}/tee-hyperlane"
  APPD="${APPD}" \
  COLLATERAL_BIN="${COLLATERAL_BIN}" \
  CELHOME="${CELHOME}" \
  CELESTIA_CHAIN_ID="${CHAINID}" \
  CELESTIA_KEY=relayer \
  TEE_HYPERLANE_DEPLOY_DIR="${REPO_DIR}/deploy" \
  TEE_COPROCESSOR_CONFIG="${CONFIG}" \
  cargo run --quiet --release -p tee-coprocessor -- run --config "${CONFIG}" \
    > "${STATE_DIR}/logs/relayer.log" 2>&1 &
  echo $! > "${STATE_DIR}/relayer.pid"
)
say "relayer log: ${STATE_DIR}/logs/relayer.log"

# The UI's deployment values normally name the live testnet. The devnet mints its ids at
# genesis, so they cannot be known in advance and are written here instead.
# Empty rather than absent when an asset was not deployed: the UI reads an empty value as
# "not on this route" and hides the control, instead of offering one that cannot work.
opt() { has "$1" && load "$1" || true; }

say "pointing the UI at the devnet"
cat > "${REPO_DIR}/bridge-app/.env.local" <<ENV
# Generated by 'make start'. Delete this file to point the UI back at the live testnet.
VITE_CELESTIA_NAME=Celestia devnet
VITE_CELESTIA_CHAIN_ID=${CHAINID}
VITE_CELESTIA_DOMAIN=${CELESTIA_DOMAIN}
VITE_CELESTIA_RPC=${CELESTIA_RPC}
VITE_CELESTIA_REST=${CELESTIA_API}
VITE_CELESTIA_EXPLORER=${CELESTIA_API}
VITE_CELESTIA_MAILBOX_ID=$(load mailbox-id)
VITE_CELESTIA_ISM_ID=$(load ism-celestia-sepolia)
VITE_CELESTIA_IGP_ID=$(load noop-hook-id)
VITE_CELESTIA_TIA_ROUTER=$(load celestia-token-id)
VITE_CELESTIA_USDC_ROUTER=$(opt celestia-usdc-token-id)
VITE_SEPOLIA_USDC_ROUTER=$(opt sepolia-usdc-router)
VITE_ARBITRUM_USDC_ROUTER=$(opt arbitrum-usdc-router)
VITE_BASE_USDC_ROUTER=$(opt base-usdc-router)
# No proving: the destination verifies the enclave's quote directly, so the only wait is the
# origin's finality plus a block.
VITE_PROVING_SECONDS=30
ENV

say "starting the bridge UI on http://localhost:3000"
(
  cd "${REPO_DIR}/bridge-app"
  [ -d node_modules ] || npm install --silent
  VITE_DEVNET=1 npm run dev -- --port 3000 --strictPort \
    > "${STATE_DIR}/logs/ui.log" 2>&1 &
  echo $! > "${STATE_DIR}/ui.pid"
)

say "devnet is running"
echo
echo "  UI        http://localhost:3000"
echo "  relayer   ${STATE_DIR}/logs/relayer.log"
echo "  chain     ${CELESTIA_RPC}"
echo
echo "'make stop' tears it down and deletes the phala instance."
